#! /usr/bin/env python

from __future__ import print_function

if __name__ == '__main__':
    from liblax.parser import run
    from optparse import OptionParser
    
    parser   = OptionParser()
    parser.add_option("-c", "--code", action='store', dest="code", help="Example: lax - c 'x ** 2 - 1'")
    (opt, args) = parser.parse_args()
    
    print(run(opt.code))
    



